import {
  pgTable,
  uuid,
  text,
  timestamp,
  integer,
  numeric,
  pgEnum,
  date,
  index,
  jsonb,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { organizations } from "./organizations";
import { suppliers } from "./suppliers";
import { products } from "./products";
import { warehouses } from "./warehouses";
import { users } from "./users";

// 발주서 상태
export const orderStatusEnum = pgEnum("order_status", [
  "draft", // 초안
  "pending", // 검토대기
  "approved", // 승인됨
  "ordered", // 발주완료 (PO 발행)
  "confirmed", // 공급자 확인
  "shipped", // 출하됨
  "partially_received", // 부분입고
  "received", // 입고완료
  "completed", // 완료
  "cancelled", // 취소
]);

// 발주서
export const purchaseOrders = pgTable("purchase_orders", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id")
    .references(() => organizations.id, { onDelete: "cascade" })
    .notNull(),
  destinationWarehouseId: uuid("destination_warehouse_id")
    .references(() => warehouses.id, { onDelete: "cascade" })
    .notNull(),
  orderNumber: text("order_number").notNull(), // 발주번호 (PO-2024-001)
  supplierId: uuid("supplier_id").references(() => suppliers.id, { onDelete: "set null" }),
  status: orderStatusEnum("status").default("draft").notNull(),
  // 금액
  totalAmount: integer("total_amount").default(0), // 총 발주금액 (원)
  // 날짜
  orderDate: date("order_date"), // 발주일
  expectedDate: date("expected_date"), // 예상입고일
  actualDate: date("actual_date"), // 실제입고일
  requestedDate: date("requested_date"), // 요청일 (입고 희망일)
  firstReceiptDate: date("first_receipt_date"), // 1차 입고일
  secondReceiptDate: date("second_receipt_date"), // 2차 입고일
  // 담당자
  createdById: uuid("created_by_id").references(() => users.id, {
    onDelete: "set null",
  }),
  approvedById: uuid("approved_by_id").references(() => users.id, {
    onDelete: "set null",
  }),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  // 스코어링 (자동발주 시)
  priorityScore: numeric("priority_score", { precision: 5, scale: 2 }), // 우선순위 점수 (0-100)
  isAutoGenerated: timestamp("is_auto_generated"), // null이면 수동발주
  notes: text("notes"),
  // Soft Delete
  deletedAt: timestamp("deleted_at", { withTimezone: true }), // null이면 활성
  deletedBy: uuid("deleted_by"), // 삭제 실행자
  deletionReason: text("deletion_reason"), // 삭제 사유
  deletionMetadata: jsonb("deletion_metadata").default({}), // 삭제 전 스냅샷
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("purchase_orders_org_status_idx").on(table.organizationId, table.status),
  index("purchase_orders_org_date_idx").on(table.organizationId, table.orderDate),
  index("purchase_orders_supplier_idx").on(table.supplierId),
  index("purchase_orders_dest_warehouse_idx").on(table.destinationWarehouseId),
  // 부분 인덱스: soft-delete 쿼리 성능 최적화 (deleted_at IS NULL인 행만 인덱싱)
  index("purchase_orders_org_active_idx").on(table.organizationId).where(sql`deleted_at IS NULL`),
]);

// 발주 항목
export const purchaseOrderItems = pgTable("purchase_order_items", {
  id: uuid("id").primaryKey().defaultRandom(),
  purchaseOrderId: uuid("purchase_order_id")
    .references(() => purchaseOrders.id, { onDelete: "cascade" })
    .notNull(),
  productId: uuid("product_id")
    .references(() => products.id, { onDelete: "cascade" })
    .notNull(),
  quantity: integer("quantity").notNull(), // 발주수량
  unitPrice: integer("unit_price").notNull(), // 단가 (원)
  totalPrice: integer("total_price").notNull(), // 금액 (수량 × 단가)
  receivedQuantity: integer("received_quantity").default(0), // 입고된 수량
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("purchase_order_items_po_idx").on(table.purchaseOrderId),
  index("purchase_order_items_product_idx").on(table.productId),
]);

export type PurchaseOrder = typeof purchaseOrders.$inferSelect;
export type NewPurchaseOrder = typeof purchaseOrders.$inferInsert;
export type PurchaseOrderItem = typeof purchaseOrderItems.$inferSelect;
export type NewPurchaseOrderItem = typeof purchaseOrderItems.$inferInsert;
